// Code generated by protoc-gen-zig
 ///! package k8s.io.apimachinery.pkg.api.resource
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

pub const Quantity = struct {
    /// Quantity string, e.g. "100m", "1Gi", "500".
    /// K8s serializes Quantity as a plain string in JSON.
    raw: ?[]const u8 = null,

    pub fn fromString(s: []const u8) Quantity {
        return .{ .raw = s };
    }

    pub fn string(self: Quantity) ?[]const u8 {
        return self.raw;
    }

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !Quantity {
        switch (try source.nextAllocMax(allocator, .alloc_always, options.max_value_len.?)) {
            .allocated_string => |s| return .{ .raw = s },
            .null => return .{ .raw = null },
            else => return error.UnexpectedToken,
        }
    }

    pub fn jsonStringify(self: *const Quantity, jws: anytype) !void {
        if (self.raw) |r| {
            try jws.write(r);
        } else {
            try jws.write(null);
        }
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !Quantity {
        _ = allocator;
        _ = options;
        return switch (source) {
            .string => |s| .{ .raw = s },
            .null => .{ .raw = null },
            else => error.UnexpectedToken,
        };
    }
};

/// QuantityValue makes it possible to use a Quantity as value for a command
/// line parameter.
/// 
/// +protobuf=true
/// +protobuf.embed=string
/// +protobuf.options.marshal=false
/// +protobuf.options.(gogoproto.goproto_stringer)=false
/// +k8s:deepcopy-gen=true
/// +k8s:openapi-model-package=io.k8s.apimachinery.pkg.api.resource
pub const QuantityValue = struct {
    string: ?[]const u8 = null,

    pub const _desc_table = .{
        .string = fd(1, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }
    
    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }
  
    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

};
