// Code generated by protoc-gen-zig
 ///! package k8s.io.apimachinery.pkg.util.intstr
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

pub const IntOrString = struct {
    /// IntOrString can hold either an integer or a string value.
    /// K8s serializes this as either a bare integer or a bare string in JSON.
    value: union(enum) {
        int: i32,
        string: []const u8,
    } = .{ .int = 0 },

    pub fn fromInt(v: i32) IntOrString {
        return .{ .value = .{ .int = v } };
    }

    pub fn fromString(s: []const u8) IntOrString {
        return .{ .value = .{ .string = s } };
    }

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !IntOrString {
        switch (try source.nextAllocMax(allocator, .alloc_always, options.max_value_len.?)) {
            .allocated_number => |s| {
                const n = std.fmt.parseInt(i32, s, 10) catch return error.UnexpectedToken;
                return .{ .value = .{ .int = n } };
            },
            .number => |s| {
                const n = std.fmt.parseInt(i32, s, 10) catch return error.UnexpectedToken;
                return .{ .value = .{ .int = n } };
            },
            .allocated_string => |s| return .{ .value = .{ .string = s } },
            .string => |s| return .{ .value = .{ .string = s } },
            else => return error.UnexpectedToken,
        }
    }

    pub fn jsonStringify(self: *const IntOrString, jws: anytype) !void {
        switch (self.value) {
            .int => |v| try jws.write(v),
            .string => |s| try jws.write(s),
        }
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !IntOrString {
        _ = allocator;
        _ = options;
        return switch (source) {
            .integer => |n| .{ .value = .{ .int = @intCast(n) } },
            .string => |s| .{ .value = .{ .string = s } },
            else => error.UnexpectedToken,
        };
    }
};
