// Code generated by protoc-gen-zig
 ///! package k8s.io.apimachinery.pkg.runtime
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

/// RawExtension is used to hold extensions in external versions.
/// 
/// To use this, make a field which has RawExtension as its type in your external, versioned
/// struct, and Object in your internal struct. You also need to register your
/// various plugin types.
/// 
/// Internal package:
/// 
///     type MyAPIObject struct {
///         runtime.TypeMeta `json:",inline"`
///         MyPlugin runtime.Object `json:"myPlugin"`
///     }
/// 
///     type PluginA struct {
///         AOption string `json:"aOption"`
///     }
/// 
/// External package:
/// 
///     type MyAPIObject struct {
///         runtime.TypeMeta `json:",inline"`
///         MyPlugin runtime.RawExtension `json:"myPlugin"`
///     }
/// 
///     type PluginA struct {
///         AOption string `json:"aOption"`
///     }
/// 
/// On the wire, the JSON will look something like this:
/// 
///     {
///         "kind":"MyAPIObject",
///         "apiVersion":"v1",
///         "myPlugin": {
///             "kind":"PluginA",
///             "aOption":"foo",
///         },
///     }
/// 
/// So what happens? Decode first uses json or yaml to unmarshal the serialized data into
/// your external MyAPIObject. That causes the raw JSON to be stored, but not unpacked.
/// The next step is to copy (using pkg/conversion) into the internal struct. The runtime
/// package's DefaultScheme has conversion functions installed which will unpack the
/// JSON stored in RawExtension, turning it into the correct object type, and storing it
/// in the Object. (TODO: In the case where the object is of an unknown type, a
/// runtime.Unknown object will be created and stored.)
/// 
/// +k8s:deepcopy-gen=true
/// +protobuf=true
/// +k8s:openapi-gen=true
pub const RawExtension = struct {
    raw: ?[]const u8 = null,

    pub const _desc_table = .{
        .raw = fd(1, .{ .scalar = .bytes }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }
    
    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }
  
    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

};

/// TypeMeta is shared by all top level objects. The proper way to use it is to inline it in your type,
/// like this:
/// 
///     type MyAwesomeAPIObject struct {
///          runtime.TypeMeta    `json:",inline"`
///          ... // other fields
///     }
/// 
/// func (obj *MyAwesomeAPIObject) SetGroupVersionKind(gvk *metav1.GroupVersionKind) { metav1.UpdateTypeMeta(obj,gvk) }; GroupVersionKind() *GroupVersionKind
/// 
/// TypeMeta is provided here for convenience. You may use it directly from this package or define
/// your own with the same fields.
/// 
/// +k8s:deepcopy-gen=false
/// +protobuf=true
/// +k8s:openapi-gen=true
pub const TypeMeta = struct {
    apiVersion: ?[]const u8 = null,
    kind: ?[]const u8 = null,

    pub const _desc_table = .{
        .apiVersion = fd(1, .{ .scalar = .string }),
        .kind = fd(2, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }
    
    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }
  
    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

};

/// Unknown allows api objects with unknown types to be passed-through. This can be used
/// to deal with the API objects from a plug-in. Unknown objects still have functioning
/// TypeMeta features-- kind, version, etc.
/// TODO: Make this object have easy access to field based accessors and settors for
/// metadata and field mutatation.
/// 
/// +k8s:deepcopy-gen=true
/// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
/// +protobuf=true
/// +k8s:openapi-gen=true
pub const Unknown = struct {
    typeMeta: ?TypeMeta = null,
    raw: ?[]const u8 = null,
    contentEncoding: ?[]const u8 = null,
    contentType: ?[]const u8 = null,

    pub const _desc_table = .{
        .typeMeta = fd(1, .submessage),
        .raw = fd(2, .{ .scalar = .bytes }),
        .contentEncoding = fd(3, .{ .scalar = .string }),
        .contentType = fd(4, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }
    
    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }
  
    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }

};
